IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ContactUsFormLog]') AND type IN (N'U'))
	DROP TABLE [dbo].[ContactUsFormLog]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ContactUsFormLog]') AND type IN (N'U'))
	BEGIN
	CREATE TABLE [dbo].[ContactUsFormLog](
		[ID] [INT] IDENTITY(1,1) NOT NULL,
		[Name] [VARCHAR](255) NOT NULL,
		[Email] [VARCHAR](255) NOT NULL,
		[Comment] [NVARCHAR](255) NOT NULL,
		[IPAddress] NVARCHAR(50),
		[LastUpdated] [DATETIME2](7) NOT NULL,
	 CONSTRAINT [PK_ContactUsFormLog] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
	END
GO

